### ISSUE TITLE
original repo is back

### ISSUE THREAD

**Issue by MattDMo** [LeonardoGentile/ColorSchemeEditorLive#1]
I was about to install this repo manually when I went to Package Control and found [this](https://packagecontrol.io/packages/ColorSchemeEditor). Apparently the author also found a copy and has [reposted](https://github.com/bobef/ColorSchemeEditor) it. I don't know if you want to keep this one up or just point to his repo, I'm sure you could talk to him and see what he thinks.

**Comment by LeonardoGentile** [comment]
@MattDMo thanks for reporting it
I will update the readme and keep this repo only as a safe backup copy  :+1:
